---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:
  - port: 80
    targetPort: 8200
    nodePort: 30123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:latest
        ports:
        - containerPort: 8200
        env:
        - name: "VAULT_LOCAL_CONFIG"
          value: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
        - name: "VAULT_SA_NAME"
          value: "value"
        - name: "SA_JWT_TOKEN"
          value: "value"
        - name: "SA_CA_CRT"
          value: "value"
        - name: "K8S_HOST"
          value: "value"
        volumeMounts:
        - mountPath: /logs
          name: logs
        - mountPath: /file
          name: file
        command: ["vault auth enable kubernetes"]
      volumes:
        - name: logs
          hostPath:
            path: /home/
        - name: file
          hostPath:
            path: /home/
# docker run -p 8200 -d -v /Users/mneepe1/test2/vaulttesting/vault/config:/vault/config --cap-add=IPC_LOCK -e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}' -e 'VAULT_API_ADDR=http://localhost:8200' -e 'VAULT_ADDR=http://localhost:8200' -it vault server
